# Generated by Django 3.2.10 on 2021-12-28 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeenotification',
            name='interview',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.interview'),
        ),
    ]
